Bundle scroll-time polyfill into library
MurhafSousli/ngx-scrollbar pull request #582
Opened 2024-04-22 10:22 UTC by Smarthard

resolves #572

I was able to figure out why tests were failing. Karma just wasn't serving new library's assets directory. Sorry to kept you waiting.

I added polyfill as is. Not sure if we actually need to provide a license notice or something like that there. But as soon as original repository will provide a proper npm package we could be able to remove it from here and work with it as a plain dependency.

2024-04-23 16:57 UTC, MurhafSousli commented
@Smarthard Thanks for the PR! could you double check why local coverage is broken

2024-04-23 19:38 UTC, Smarthard commented
@MurhafSousli not sure. Probably your CI workflow missing `write` permission. At least that's what I found at [marocchino/sticky-pull-request-comment readme](https://github.com/marocchino/sticky-pull-request-comment?tab=readme-ov-file#basic). Here is the related issue: https://github.com/marocchino/sticky-pull-request-comment/issues/298

2024-04-24 14:57 UTC, MurhafSousli commented
@Smarthard I opened a PR to test the build, it has no issue https://github.com/MurhafSousli/ngx-scrollbar/pull/585

Weird, perhaps it couldn't comment on the PR cause it is opened by you?

2024-04-24 16:16 UTC, Smarthard commented
I created a test branch with changes similar to yours in #585 and opened PRs #586 here and https://github.com/Smarthard/ngx-scrollbar/pull/1 in my fork to test if it really a permission's issue

2024-04-24 16:52 UTC, Smarthard commented
@MurhafSousli Yeah looks like you were right. My changes passed workflow in my repo and failed in yours. I think you need something like this to solve this issues with permissions.

```patch
diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
index 7ffcc0e..2729b37 100644
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -8,6 +8,10 @@ on:
 
 jobs:
   build:
+    # Allow forks to be annotated with code coverage properly
+    permissions:
+      pull-requests: write
+
     # Machine environment:
     # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
     runs-on: ubuntu-latest
```

2024-04-25 17:48 UTC, MurhafSousli commented
I fixed the CI build issue, I got a question, the script is copied to assets directory of the plugin. but how would be copied to the user's app assets directory? would that happen automatically?

2024-04-26 12:33 UTC, Smarthard commented
> I fixed the CI build issue, I got a question, the script is copied to assets directory of the plugin. but how would be copied to the user's app assets directory? would that happen automatically?

By including it from `angular.json` build options as any other assets I suppose. Yeah it's a breaking change

2024-04-27 08:41 UTC, MurhafSousli commented
> > I fixed the CI build issue, I got a question, the script is copied to assets directory of the plugin. but how would be copied to the user's app assets directory? would that happen automatically?
> 
> By including it to `angular.json` build options as any other assets I suppose. Yeah it's a breaking change
> 
> UPD something like this should work (I removed unnecessary lines):
> 
> ```json
> {
>     "projects": {
>         "app": {
>             "architect": {
>                 "build": {
>                     "builder": "@angular-devkit/build-angular:browser",
>                     "options": {
>                         "assets": [
>                             {
>                                 "glob": "**/*",
>                                 "input": "node_modules/ngx-scrollbar/assets/",
>                                 "output": "assets"
>                             }
>                         ],
>                     }
>                 }
>             }
>         }
>     }
> }
> ```

In this case, I want to keep loading the script from the github link as the default option, without breaking changes and the only change in this PR would be the shipping of the script with the package.

We can add to the documentation the changes needed to load it manually from the assets directory.

2024-04-27 08:46 UTC, MurhafSousli requested changes
In this case, I want to keep loading the script from the github link as the default option, without breaking changes and the only change in this PR would be the shipping of the script with the package.

We can add to the documentation the changes needed to load it manually from the assets directory.

2024-04-27 08:46 UTC, MurhafSousli commented on projects/ngx-scrollbar/karma.conf.js
Reset

2024-04-27 08:46 UTC, MurhafSousli commented on projects/ngx-scrollbar/src/lib/tests/scrollbar-manager.spec.ts
Reset

2024-04-27 08:46 UTC, MurhafSousli commented on projects/ngx-scrollbar/src/lib/utils/scrollbar-manager.ts
Reset

2024-04-27 08:46 UTC, MurhafSousli commented on projects/ngx-scrollbar-demo/server.ts
Reset

2024-04-30 13:03 UTC, Smarthard commented
@MurhafSousli Hello!

I updated PR as you required. All changes were squashed into single commit and force-pushed to make it clearer.

2024-05-30 19:25 UTC, MurhafSousli commented
@leblancmeneses I don't get it, in Chrome the polypill script will not even load, and the URL is stored as a string value. what is the complaint about?

2024-05-30 22:39 UTC, merged

2024-05-30 23:36 UTC, MurhafSousli commented
@Smarthard Sorry for the late response. I added the documentation here https://github.com/MurhafSousli/ngx-scrollbar/wiki/Scroll-timeline-polyfill

2024-05-31 11:45 UTC, Smarthard commented
@MurhafSousli no worries! Thanks! I just tested and it's working great.

One good thing to point out for anyone who will use it that way. I needed to additionally modify my CSP rules for style-src like this: `style-src 'unsafe-inline' blob:`. That's because polyfill trying to dynamically assign styles via `createObjectURL`.

For future references I'd like to left an example how I handled these changes for my project: https://github.com/Smarthard/shikicinema/commit/c5ae774c92782718078c1b407a007912730f3a49

2024-05-31 11:45 UTC, Smarthard commented
@leblancmeneses frankly, from my experience moderators from Chrome Web Store often falsy-positive report issues on items to their developers. My recommendation is to reply to CWS from email message you receive (look closely for reply contacts). You could describe there your concerns about false-positive alert and provide them references from your code and/or references from the software your are using.

2024-05-31 12:41 UTC, MurhafSousli commented
@Smarthard  Is this related https://github.com/MurhafSousli/ngx-scrollbar/issues/590 or this https://github.com/MurhafSousli/ngx-scrollbar/issues/594 related?

2024-05-31 13:07 UTC, Smarthard commented
> Is https://github.com/MurhafSousli/ngx-scrollbar/issues/590 or https://github.com/MurhafSousli/ngx-scrollbar/issues/594 related?

I think I've seen those kind of errors in my console as well, but after CSP correction there are no errors.

>It would be beneficial if you could add a how-to make it work with CSP at the end at this documentation

For common SSR/CSR angular web apps this should be sufficient:

```html
<!-- index.html -->
<meta http-equiv="Content-Security-Policy" content="style-src 'unsafe-src' blob:">
```

For web extensions you would need to modify `manifest.json` of your extension, changes to `index.html` are not necessary in this case:

```json
"content_security_policy": "style-src 'unsafe-src' blob:"
```

2024-05-31 13:11 UTC, leblancmeneses commented
@MurhafSousli

After removing the string with patch-package, my Chrome extension was approved. 
https://chromewebstore.google.com/detail/tabsift/gihejcnfnbdiohnjepkkdhilfedjcahm?hl=en&authuser=0

I think the best solution here would be to bump the major version and change NG_SCROLLBAR_POLYFILL

```
export type PolyFillLoader = (url: string) => Promise<void>;
export const NG_SCROLLBAR_POLYFILL = new InjectionToken<PolyFillLoader>('NG_SCROLLBAR_POLYFILL');
```

and figure out a way to make it tree-shakable for consumers wanting to override the current default behavior.

Thanks for maintaining this!

@Smarthard , This violation is pretty clear 'modules pointing to external files'.

2024-05-31 17:34 UTC, MurhafSousli commented
So if any variable contains a string value of an external URL would be rejected even if it is never used at runtime! that's weird